"""
Transaction Manager for OCPP 2.0.1.

Manages transaction lifecycle for OCPP 2.0.1, which uses TransactionEvent
instead of StartTransaction/StopTransaction. Generates UUID transaction
IDs and tracks sequence numbers per transaction.

In OCPP 2.0.1:
- Transaction IDs are UUID strings generated by the Charge Point
- Each TransactionEvent within a transaction carries a monotonically
  increasing sequence number (seq_no)
- TransactionEvent replaces StartTransaction/StopTransaction

Classes:
    TransactionManagerV201: OCPP 2.0.1 transaction state tracker.
    TxStartStopPointConfig: Configure which physical events trigger TransactionEvent(Started).
"""

import uuid
from dataclasses import dataclass
from typing import Optional

from chargeghost_evse.engine.connector import ConnectorState


@dataclass
class TxStartStopPointConfig:
    """
    Configure which physical events trigger TransactionEvent(Started).

    OCPP 2.0.1 allows the Charge Point to decide what triggers the
    TransactionEvent(Started) message. This config controls the mapping
    from engine events to the trigger_reason reported in TransactionEvent.

    Attributes:
        start_on_ev_connected: If True, TransactionEvent(Started) is sent when
            the EV connects (cable plugged in), before authorization.
        start_on_authorized: If True, TransactionEvent(Started) is sent when
            authorization is confirmed. If both start_on_ev_connected and
            start_on_authorized are True, authorization takes precedence.
        start_on_energy_transfer: If True, TransactionEvent(Started) is sent
            when energy transfer begins (charging session starts).
    """

    start_on_ev_connected: bool = False
    start_on_authorized: bool = True
    start_on_energy_transfer: bool = False

    def trigger_reason_for_start(
        self,
        ev_connected: bool = False,
        authorized: bool = False,
        energy_transfer: bool = False,
    ) -> Optional[str]:
        """
        Determine the trigger reason for TransactionEvent(Started).

        Args:
            ev_connected: Whether the EV is physically connected.
            authorized: Whether authorization has been confirmed.
            energy_transfer: Whether energy transfer has begun.

        Returns:
            The trigger reason string, or None if no start condition is met.
        """
        if self.start_on_energy_transfer and energy_transfer:
            return "EnergyTransfer"
        if self.start_on_authorized and authorized:
            return "Authorized"
        if self.start_on_ev_connected and ev_connected:
            return "CablePluggedIn"
        return None


_CHARGE_STATE_MAP: dict[ConnectorState, str] = {
    ConnectorState.CHARGING: "Charging",
    ConnectorState.SUSPENDED_EV: "SuspendedEV",
    ConnectorState.SUSPENDED_EVSE: "SuspendedEVSE",
}


def connector_state_to_charging_state(
    state: ConnectorState,
) -> Optional[str]:
    """
    Map a ConnectorState to OCPP 2.0.1 ChargingStateEnumType value.

    Args:
        state: The connector state to map.

    Returns:
        ChargingStateEnumType string value, or None if state is not a charging state.
    """
    return _CHARGE_STATE_MAP.get(state)


_TRIGGER_REASON_MAP: dict[str, str] = {
    "CablePluggedIn": "CablePluggedIn",
    "Authorized": "Authorized",
    "ChargingStateChanged": "ChargingStateChanged",
    "ChargingRateChanged": "ChargingRateChanged",
    "MeterValuePeriodic": "MeterValuePeriodic",
    "MeterValueClock": "MeterValueClock",
    "EVDeparted": "EVDeparted",
    "StopRequested": "StopRequested",
    "DeAuthorized": "DeAuthorized",
    "EnergyLimitReached": "EnergyLimitReached",
    "Trigger": "Trigger",
    "UnlockCommand": "UnlockCommand",
    "RemoteStart": "RemoteStart",
    "RemoteStop": "RemoteStop",
}


def engine_event_to_trigger_reason(event: str) -> str:
    """
    Map an engine event string to TriggerReasonEnumType value.

    All 14 OCPP 2.0.1 trigger reasons are supported.

    Args:
        event: The engine event string.

    Returns:
        The corresponding TriggerReasonEnumType string.
    """
    return _TRIGGER_REASON_MAP.get(event, "Trigger")


class TransactionManagerV201:
    """
    Manages OCPP 2.0.1 transaction identifiers and sequence numbers.

    Tracks active transactions keyed by EVSE ID and provides generation
    of UUID transaction IDs compatible with the OCPP 2.0.1
    TransactionEvent message model.

    Supports offline sequence number persistence for replay after reconnect.

    Attributes:
            _transactions: Map of evse_id to active transaction_id (UUID string).
            _seq_numbers: Map of transaction_id to next sequence number.
            _pending_seq_persistence: Seq numbers awaiting flush to persistent storage.
    """

    def __init__(self) -> None:
        self._transactions: dict[int, str] = {}
        self._seq_numbers: dict[str, int] = {}
        self._tx_metadata: dict[str, dict] = {}

    def begin_transaction(self, evse_id: int) -> str:
        """
        Start a new transaction for the given EVSE.

        Generates a UUID transaction ID and initialises its
        sequence counter at zero.

        Args:
                evse_id: The EVSE identifier starting the transaction.

        Returns:
                The generated UUID transaction ID string.
        """
        tx_id = str(uuid.uuid4())
        self._transactions[evse_id] = tx_id
        self._seq_numbers[tx_id] = 0
        self._tx_metadata[tx_id] = {
            "evse_id": evse_id,
        }
        return tx_id

    def get_transaction_id(self, evse_id: int) -> Optional[str]:
        """
        Get the active transaction ID for an EVSE.

        Args:
                evse_id: The EVSE identifier.

        Returns:
                Transaction ID string, or None if no active transaction.
        """
        return self._transactions.get(evse_id)

    def get_next_seq_no(self, transaction_id: str) -> int:
        """
        Get and increment the sequence number for a transaction.

        Returns the current sequence number and advances the counter by one.

        Args:
                transaction_id: The transaction identifier.

        Returns:
                The current sequence number (before increment).
        """
        seq = self._seq_numbers.get(transaction_id, 0)
        self._seq_numbers[transaction_id] = seq + 1
        return seq

    def get_current_seq_no(self, transaction_id: str) -> int:
        """
        Get the current sequence number without incrementing.

        Args:
                transaction_id: The transaction identifier.

        Returns:
                The current sequence number.
        """
        return self._seq_numbers.get(transaction_id, 0)

    def end_transaction(self, evse_id: int) -> Optional[str]:
        """
        End the active transaction for an EVSE.

        Removes the transaction and its sequence counter from tracking.

        Args:
                evse_id: The EVSE identifier ending the transaction.

        Returns:
                The ended transaction ID, or None if no active transaction.
        """
        tx_id = self._transactions.pop(evse_id, None)
        if tx_id is not None:
            self._seq_numbers.pop(tx_id, None)
            self._tx_metadata.pop(tx_id, None)
        return tx_id

    @property
    def active_transactions(self) -> dict[int, str]:
        """Return a copy of the active transactions map."""
        return dict(self._transactions)

    def get_all_seq_numbers(self) -> dict[str, int]:
        """
        Get all transaction IDs and their current sequence numbers.

        Used for offline persistence so seq_no state can be restored
        after a reconnect.

        Returns:
                Dict mapping transaction_id to current seq_no.
        """
        return dict(self._seq_numbers)

    def restore_seq_numbers(self, seq_data: dict[str, int]) -> None:
        """
        Restore transaction sequence numbers from persisted state.

        Used after reconnect to resume sequence numbering from where
        we left off.

        Args:
                seq_data: Dict mapping transaction_id to seq_no to restore.
        """
        for tx_id, seq_no in seq_data.items():
            self._seq_numbers[tx_id] = seq_no
