"""
Transaction Manager for OCPP 2.0.1.

Manages transaction lifecycle for OCPP 2.0.1, which uses TransactionEvent
instead of StartTransaction/StopTransaction. Generates unique transaction
IDs (strings) and tracks sequence numbers per transaction.

In OCPP 2.0.1:
- Transaction IDs are strings generated by the Charge Point
- Each TransactionEvent within a transaction carries a monotonically
  increasing sequence number (seq_no)
- TransactionEvent replaces StartTransaction/StopTransaction

Classes:
    TransactionManagerV201: OCPP 2.0.1 transaction state tracker.
"""

from typing import Optional


class TransactionManagerV201:
    """
    Manages OCPP 2.0.1 transaction identifiers and sequence numbers.

    Tracks active transactions keyed by EVSE ID and provides generation
    of unique string transaction IDs compatible with the OCPP 2.0.1
    TransactionEvent message model.

    Attributes:
            _transactions: Map of evse_id to active transaction_id.
            _seq_numbers: Map of transaction_id to next sequence number.
    """

    def __init__(self) -> None:
        self._next_id: int = 0
        self._transactions: dict[int, str] = {}
        self._seq_numbers: dict[str, int] = {}

    def begin_transaction(self, evse_id: int) -> str:
        """
        Start a new transaction for the given EVSE.

        Generates a unique string transaction ID and initialises its
        sequence counter at zero.

        Args:
                evse_id: The EVSE identifier starting the transaction.

        Returns:
                The generated transaction ID string.
        """
        self._next_id += 1
        tx_id = str(self._next_id)
        self._transactions[evse_id] = tx_id
        self._seq_numbers[tx_id] = 0
        return tx_id

    def get_transaction_id(self, evse_id: int) -> Optional[str]:
        """
        Get the active transaction ID for an EVSE.

        Args:
                evse_id: The EVSE identifier.

        Returns:
                Transaction ID string, or None if no active transaction.
        """
        return self._transactions.get(evse_id)

    def get_next_seq_no(self, transaction_id: str) -> int:
        """
        Get and increment the sequence number for a transaction.

        Returns the current sequence number and advances the counter by one.

        Args:
                transaction_id: The transaction identifier.

        Returns:
                The current sequence number (before increment).
        """
        seq = self._seq_numbers.get(transaction_id, 0)
        self._seq_numbers[transaction_id] = seq + 1
        return seq

    def end_transaction(self, evse_id: int) -> Optional[str]:
        """
        End the active transaction for an EVSE.

        Removes the transaction and its sequence counter from tracking.

        Args:
                evse_id: The EVSE identifier ending the transaction.

        Returns:
                The ended transaction ID, or None if no active transaction.
        """
        tx_id = self._transactions.pop(evse_id, None)
        if tx_id is not None:
            self._seq_numbers.pop(tx_id, None)
        return tx_id

    @property
    def active_transactions(self) -> dict[int, str]:
        """Return a copy of the active transactions map."""
        return dict(self._transactions)
